apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-test-ha-application-without-redis-deployment
  labels:
    app: kubernetes-test-ha-application-without-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-test-ha-application-without-redis
  template:
    metadata:
      labels:
        app: kubernetes-test-ha-application-without-redis
    spec:
      containers:
        - name: kubernetes-test-ha-application-without-redis
          image: quay.io/zparnold/packt-kubernetes-demo-app:without_redis_v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-test-ha-application-without-redis
  labels:
    app: kubernetes-test-ha-application-without-redis
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: kubernetes-test-ha-application-without-redis